### PR TITLE
APP-3296 Add .devx-cicd/config.yaml

### PR DESCRIPTION
**Pull request by micaste**
### Ticket
[APP-3296](https://perzoinc.atlassian.net/browse/APP-3296)

### Description
Laying out the ground work for integrating this project into the Devx-cicd pipeline.
For the documentation about the config.yaml file, see https://github.com/micaste/devx-cicd/blob/APP-3296/docs/configYaml.md
Or about the project in general, see my PR: https://github.com/SymphonyOSF/devx-cicd/pull/1

### Dependencies
List the other pull requests that should be merged before/along this one.

### Checklist
- [X] Referenced a ticket in the PR title and in the corresponding section
- [X] Filled properly the description and dependencies, if any
- [X] Unit tests updated or added
- [X] Javadoc added or updated
- [X] Updated the documentation in [docs folder](../docs)

### CODE REVIEW

**Comment by micaste** [comment]
I get this error during the 2nd command :
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':symphony-bdk-bom:signBomPublication'.
> Cannot perform signing task ':symphony-bdk-bom:signBomPublication' because it has no configured signatory
```

So maybe I'll look into it before merging

**Comment by symphony-thibault** [comment]
> @micaste I get this error during the 2nd command

@symphony-elias could help you on that point

**Review by symphony-thibault — APPROVED** [review]

**Comment by symphony-hong** [comment]
@micaste I guess the cause is that you tried to publish a stable version `1.6.0-SNAPSHOT-stable`, then gradle will understand this version as a release version (because it doesn't end with `SNAPSHOT`), then the signing step was not bypassed.
```ext.isReleaseVersion = !ext.projectVersion.endsWith('SNAPSHOT')```

**Review by symphony-hong — APPROVED** [review]
LGTM

**Comment by micaste** [comment]
Closing in favour of https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/370: pushing on a specific branch instead of master

**Pull request closed without merging**
