### PR TITLE
BDK2.0 Java - Missing endpoint roles-list

### PR DESCRIPTION
**Pull request by symphony-soufiane**
### Ticket
[PLAT-10436](https://perzoinc.atlassian.net/browse/PLAT-10436)

### Description
[List roles endpoint](https://developers.symphony.com/restapi/reference#list-roles)'s implementation was missing in User service. This was blocked by the usage of api-spec 2.10 release. 
On this occasion, Disclaimer service that was defined previously is mentioned in fluent-api.md file.

### Dependencies
List the other pull requests that should be merged before/along this one.

### Checklist
- [x] Referenced a ticket in the PR title and in the corresponding section
- [x] Filled properly the description and dependencies, if any
- [x] Unit tests updated or added
- [x] Javadoc added or updated
- [x] Updated the documentation in [docs folder](../docs)

### CODE REVIEW

**Comment by symphony-soufiane** [comment]
Unit test "listRoles()" will keep failing as long as  [symphony-api-spec/PLAT-10436](https://github.com/symphonyoss/symphony-api-spec/pull/92) and [SBE/PLAT-10436](https://github.com/SymphonyOSF/SBE/pull/21731) are not merged .

**Comment by symphony-youri** [comment]
Just so that we are all aware this is going to be a breaking change right? (I'm ok with the impact is limited IMHO)

**Comment by symphony-soufiane** [comment]
Switching from specs 20.9 to 20.10 breaks the generated API but this is fixed in the same PR. AFAIK this will not break anything else.
Actually the ticket for fixing this change is related to [PLAT-10427](https://perzoinc.atlassian.net/browse/PLAT-10427) but I did it in the same PR here, sorry if this was not clear/mentioned.
@symphony-youri

**Comment by symphony-youri** [comment]
Moving a class from one package to another would break the compilation/execution of an existing bot using this class

**Comment by symphony-soufiane** [comment]
You're right but still, I think this is going to be transparent for bots as it is not used in Service layer.

**Comment by symphony-elias** [comment]
> Moving a class from one package to another would break the compilation/execution of an existing bot using this class

The package move will be transparent since ExtensionAppAuthenticatorCertImpl is only using it (and is an internal class) and abstract base class AbstractExtensionAppAuthenticator is not exposing com.symphony.bdk.gen.api.model.ExtensionAppAuthenticateRequest
So for me it is good

**Review by symphony-elias — APPROVED** [review]
OK for me
LGTM

**Review by symphony-youri — APPROVED** [review]

**Comment by symphony-soufiane** [comment]
ok to test

**Pull request merged**
